### ISSUE TITLE
mysql 源增加additional_options配置参数后执行不成功

### ISSUE THREAD

**Issue by itang** [huacnlee/gobackup#12]
## 问题现象

mysql 加上配置additional_options:

`additional_options: "--single-transaction --quick"`

执行控制台输出 `mysqldump: unknown variable 'single-transaction --quick'`

## 初步分析

看代码发现`additional_options`是直接作为一个`cmd arg` 整体添加的`exec.Command`的。而Go的exec.Command 对args部分存在空格的参数支持行为有问题， 如`exec.Command("ls", "-l -a") `需要拆成`exec.Command("ls", "-l", "-a")`

## 建议

将`spaceRegexp.Split(command, -1)`逻辑应用每个arg,  类似这个逻辑: `args =  args.flat_map{|arg| spaceRegexp.Split(arg)}`

**Comment by huacnlee** [comment]
fix in 0.6.1
