### ISSUE TITLE
not clean tmp dir when exec on root permission and one job store to different destination

### ISSUE THREAD

**Issue by camuschen** [huacnlee/gobackup#20]
Amazon Linux AMI latest
gobackup -v 0.6.1

用于自动备份docker的存储，docker -v指定的目录所有者为root
所以在执行perform时使用sudo来执行
执行完毕后查看tmp/gobackup目录下的临时文件夹和tar打包文件没有被清理，需要手动清理

另，
指定一个任务时，存储目的地貌似只识别最后一项store
我有一项本地备份任务，希望在存储时，同时上传至多个不同的目的地，比如阿里OSS和aws s3。
如果拆分为两个任务，则会打包两次，生成两个压缩包和临时目录
结合上一个root下执行没有清理的问题，磁盘容量消耗非常大

请问有没有什么解决方法？谢谢~

**Comment by huacnlee** [comment]
Tmp 目录没删除的问题我也发现了，今天修复一下。

store_with 只能一个，不支持多个，而我设计的想法是没必要存储多分，尤其是项目文件大的时候，存储传输成本本来就高。你期望分别 OSS 和 S3 都存储这个无法支持，而且我也认为没有必要。

**Comment by huacnlee** [comment]
升级 0.6.2 问题已修复

**Comment by HolgerHuo** [comment]
您好～想请问一下 这个问题0.8.2还存在吗？ 我同样也是在root环境下执行备份，但在tmp下会有未加密和加密过的文件
<img width="470" alt="Screen Shot 2020-03-29 at 5 29 51 PM" src="https://user-images.githubusercontent.com/50446405/77845619-e6fb5500-71e2-11ea-80ff-0c6be13680c8.png">
<img width="456" alt="Screen Shot 2020-03-29 at 5 30 24 PM" src="https://user-images.githubusercontent.com/50446405/77845630-faa6bb80-71e2-11ea-8a5e-d5aa98b21c27.png">
