### ISSUE TITLE
unknown function: pg_catalog.set_config()

### ISSUE THREAD

**Issue by ernanieg** [huacnlee/gobackup#32]
pg_dump: [archiver (db)] query failed: ERROR:  unknown function: pg_catalog.set_config()
pg_dump: [archiver (db)] query was: SELECT pg_catalog.set_config('search_path', '', false)

An error occurred when I tried to backup a cockroachdb (postgresql) database

![image](https://user-images.githubusercontent.com/16890316/45135478-2eba2600-b1d2-11e8-91f9-3980a57675c1.png)

![image](https://user-images.githubusercontent.com/16890316/45135488-3974bb00-b1d2-11e8-96fd-81141b7013fe.png)

Here's my yml file
models:
  localhost:
    compress_with:
      type: tgz
    store_with:
      type: local
      keep: 20
      path: /home/ernanie/backup/cockroach
    databases:
      bank:
        database: bank
        type: postgresql
        host: localhost
        port: 26257
        username: root

**Comment by huacnlee** [comment]
This is looks like CockroachDB problem, you must confirm that support use `pg_dump` tool to export.
