### ISSUE TITLE
手动执行gobackup perform成功，但是定时任务提示找不到mysqldump

### ISSUE THREAD

**Issue by careylipu** [huacnlee/gobackup#44]
> [root@iZwz9ccgakmnlprso2kzxlZ ~]# crontab -l
> 0 0 * * * /usr/local/bin/gobackup perform >> ~/.gobackup/gobackup.log
> [root@iZwz9ccgakmnlprso2kzxlZ ~]# cat ~/.gobackup/gobackup.log
> 2019/07/10 00:00:01 ======== mysql ========
> 2019/07/10 00:00:01 WorkDir: /tmp/gobackup/1562688001676054782/mysql
> 
> 2019/07/10 00:00:01 ------------- Databases -------------
> 2019/07/10 00:00:01 => database | mysql : master
> 2019/07/10 00:00:01 -> Dumping MySQL...
> 2019/07/10 00:00:01 -> Dump error: mysqldump cannot be found
> 2019/07/10 00:00:01 Cleanup temp dir:/tmp/gobackup...
> 
> 2019/07/10 00:00:01 ======= End mysql =======
> 
> [root@iZwz9ccgakmnlprso2kzxlZ ~]# mysqldump
> Usage: mysqldump [OPTIONS] database [tables]
> OR mysqldump [OPTIONS] --databases [OPTIONS] DB1 [DB2 DB3...]
> OR mysqldump [OPTIONS] --all-databases [OPTIONS]
> For more options, use mysqldump --help
> [root@iZwz9ccgakmnlprso2kzxlZ ~]#
> [root@iZwz9ccgakmnlprso2kzxlZ ~]# mysql --version
> mysql Ver 15.1 Distrib 10.1.21-MariaDB, for Linux (x86_64) using readline 5.1
[root@iZwz9ccgakmnlprso2kzxlZ ~]# mysqldump --version
mysqldump  Ver 10.16 Distrib 10.1.21-MariaDB, for Linux (x86_64)
[root@iZwz9ccgakmnlprso2kzxlZ ~]# 
[root@iZwz9ccgakmnlprso2kzxlZ ~]# gobackup --version
gobackup version 0.8.0

**Comment by careylipu** [comment]
> [root@iZwz9ccgakmnlprso2kzxlZ ~]# crontab -l
> 0 0 * * * /usr/local/bin/gobackup perform >> ~/.gobackup/gobackup.log
> [root@iZwz9ccgakmnlprso2kzxlZ ~]# cat ~/.gobackup/gobackup.log
> 2019/07/10 00:00:01 ======== mysql ========
> 2019/07/10 00:00:01 WorkDir: /tmp/gobackup/1562688001676054782/mysql
> 
> 2019/07/10 00:00:01 ------------- Databases -------------
> 2019/07/10 00:00:01 => database | mysql : master
> 2019/07/10 00:00:01 -> Dumping MySQL...
> 2019/07/10 00:00:01 -> Dump error: mysqldump cannot be found
> 2019/07/10 00:00:01 Cleanup temp dir:/tmp/gobackup...
> 
> 2019/07/10 00:00:01 ======= End mysql =======
> 
> [root@iZwz9ccgakmnlprso2kzxlZ ~]# mysqldump
> Usage: mysqldump [OPTIONS] database [tables]
> OR mysqldump [OPTIONS] --databases [OPTIONS] DB1 [DB2 DB3...]
> OR mysqldump [OPTIONS] --all-databases [OPTIONS]
> For more options, use mysqldump --help
> [root@iZwz9ccgakmnlprso2kzxlZ ~]#
> [root@iZwz9ccgakmnlprso2kzxlZ ~]# mysql --version
> mysql Ver 15.1 Distrib 10.1.21-MariaDB, for Linux (x86_64) using readline 5.1
[root@iZwz9ccgakmnlprso2kzxlZ ~]# mysqldump --version
mysqldump  Ver 10.16 Distrib 10.1.21-MariaDB, for Linux (x86_64)
[root@iZwz9ccgakmnlprso2kzxlZ ~]#

**Comment by huacnlee** [comment]
```bash
$ which mysqldump
$ ln /path/to/mysqldump /usr/local/bin/
```

**Comment by careylipu** [comment]
Thanks！
$ which mysqldump
$ ln -s /usr/local/mysql/bin/mysqldump /usr/local/bin/

**Comment by careylipu** [comment]
ln -s /usr/local/mysql/bin/mysqldump /usr/local/bin/
我是挂在的分区，无法创建硬链接，创建的软连接。今天检查日志发现和昨天一样。
