### ISSUE TITLE
please consider using pigz or gzip with multiple cores and split the backup file

### ISSUE THREAD

**Issue by changchichung** [huacnlee/gobackup#47]
thanks for the wonderful tool .
but during the compress process , gobackup only single core to run gzip , is it possible make this a configurable parameter in configuration file ?
or replace gzip with pigz for use multi cores to compress the backup file ?

and after compress , the backup file is a huge tgz , is it possible to make an option to split the backup file ?

**Comment by 40huo** [comment]
Splitting the compressed backup file is a better option.
