### ISSUE TITLE
Support restoring

### ISSUE THREAD

**Issue by JokerQyou** [huacnlee/gobackup#52]
Backup is useless if you can't conveniently restore from the archives. I know it's doable by invoking some shell commands to un-tar the archive and importing database dumps, but that is not very intuitive, let along there's no documentation at all.

I'd suggest adding a `restore` subcommand to allow users to selectively restore some part of the data.
Another solution would be to generate restore scripts (generic shell scripts) when `perform` finished.

**Comment by huacnlee** [comment]
Toooo complex, can't to support.
