### ISSUE TITLE
Docker image support?

### ISSUE THREAD

**Issue by imWildCat** [huacnlee/gobackup#54]
Hi, do you plan to support Docker image? For example, adding a `Dockerfile` and publish it to hub.docker.com?

**Comment by vacoo** [comment]
Hi! i create docker image - https://hub.docker.com/repository/docker/vacoo/gobackup

**Comment by huacnlee** [comment]
https://hub.docker.com/r/huacnlee/gobackup

**Comment by ZachCheung** [comment]
@huacnlee The current docker image won't work much since gobackup heavily relies on commands like `pg_dump` in the system which don't exists in the image. A solo gobackup in the container couldn't do many things.
