### ISSUE TITLE
Feature Request: ExpandEnv

### ISSUE THREAD

**Issue by imWildCat** [huacnlee/gobackup#55]
## Background

To use `gobackup` with Kubernetes or other tools, we need to pass credentials dynamically via environment variable.

Currently, the yaml config file is kind of static. We could leverage `os.ExpandEnv` to enable the support for environment variable.

**Comment by imWildCat** [comment]
Looks like that this app supports `ExpandEnv` because of https://github.com/spf13/viper

**Comment by bligneri** [comment]
Hi @imWildCat . I have the same issue.
Did you figure out if this was possible out of the box thanks to viper ?

**Comment by imWildCat** [comment]
@bligneri sorry, it has been too long and I forgot how I ended up with this issue.

(hello from Canada as well!)
