### ISSUE TITLE
Problem with run backup 

### ISSUE THREAD

**Issue by d1mf** [huacnlee/gobackup#57]
Hello. I have the next problem. I run the script for run backup  (centos7)
/usr/local/bin/gobackup perform >> ~/.gobackup/gobackup.log 
Backup doesn't run and log files  clean. 
![Screenshot_71](https://user-images.githubusercontent.com/10393074/78592464-cd46b700-784d-11ea-83d3-56fc0d6f1306.png)

Maybe you know where I can find debug or etc?

**Comment by fredsted** [comment]
Where do you have your config? I had it in `/etc/gobackup`, and had to delete the default config in `~/.gobackup` first.

**Comment by shirshak55** [comment]
set up default config first.

**Comment by huacnlee** [comment]
Need config first before you run `gobackup perform`.
