### ISSUE TITLE
We can run It on windows

### ISSUE THREAD

**Issue by careylipu** [huacnlee/gobackup#60]
good job！
We can run It on windows10 and Windows7：

tested：
1.mysql backup and files backup to oss
2.mysql backup and files backup to oss
3.OpenSSL - aes-256-cbc encrypt 

note:
1.win7 need install tar（http://gnuwin32.sourceforge.net/packages/libarchive.htm），win10 not need
2.win7 and win10  need install  openssl (http://gnuwin32.sourceforge.net/packages/openssl.htm),if you want aes-256-cbc encrypt

**Comment by huacnlee** [comment]
Sorry, there is no plan to do this.

**Comment by careylipu** [comment]
thank you huacnlee，In fact, the open source project can run under Windows after testing. The tar compression, ssl packaging, and mysqldump features are normal

**Comment by alexn-s** [comment]
would there be a possibility to get it to work cygwin?
